export const courses = [
  { id: 'cs12',   code: 'CS12',   name: 'Computer Science Fundamentals',      nameAr: 'أساسيات علوم الحاسب',          semester: 'First Semester', semesterAr: 'الفصل الدراسي الأول' },
  { id: 'it1231', code: 'IT1231', name: 'Information Technology Fundamentals', nameAr: 'أساسيات تقنية المعلومات',      semester: 'First Semester', semesterAr: 'الفصل الدراسي الأول' },
  { id: 'c180',   code: 'C180',   name: 'Programming Basic',                   nameAr: 'أساسيات البرمجة',              semester: 'First Semester', semesterAr: 'الفصل الدراسي الأول' },
];

export const programs = [
  { id: 'cs', code: 'CS', name: 'Computer Science',        nameAr: 'علوم الحاسب',       year: '2025/2026' },
  { id: 'it', code: 'IT', name: 'Information Technology',  nameAr: 'تقنية المعلومات',   year: '2025/2026' },
  { id: 'se', code: 'SE', name: 'Software Engineering',    nameAr: 'هندسة البرمجيات',    year: '2025/2026' },
];

export const courseReportTypes = [
  {
    id: 'course-specification',
    title: 'Course Specification',
    titleAr: 'توصيف المقرر',
    descEn: 'Course details, objectives, and teaching content',
    desc: 'تفاصيل المقرر، الأهداف، والمحتوى الدراسي',
    icon: 'ti-file-description',
    iconClass: 'ic-primary',
    highlight: 'hl-primary',
    badge: { label: 'Pending', cls: 'b-primary' },
    defaultStatus: 's-pending',
    defaultStatusLabel: 'Pending Submit',
    category: 'main',
  },
  {
    id: 'crns',
    title: 'CRNs',
    titleAr: 'أرقام الشعب',
    descEn: 'Registration numbers for sections and course groups',
    desc: 'أرقام تسجيل الأقسام والشعب الدراسية',
    icon: 'ti-list-numbers',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'course-report',
    title: 'Course Report',
    titleAr: 'تقرير المقرر',
    descEn: 'Course results and achievement level report',
    desc: 'تقرير نتائج المقرر ومستوى التحصيل',
    icon: 'ti-chart-bar',
    iconClass: 'ic-amber',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'course-portfolio',
    title: 'Course Portfolio',
    titleAr: 'ملف المقرر',
    descEn: 'Complete course portfolio and attached documents',
    desc: 'ملف المقرر الشامل والمستندات المرفقة',
    icon: 'ti-folders',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'student-survey',
    title: 'Student Survey',
    titleAr: 'استبيان الطلاب',
    descEn: 'Student feedback survey for the course and teaching',
    desc: 'استبيان رأي الطلاب في المقرر والتدريس',
    icon: 'ti-message-circle',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-done',
    defaultStatusLabel: 'Approved',
    category: 'additional',
  },
  {
    id: 'peer-review',
    title: 'Peer Review',
    titleAr: 'مراجعة النظراء',
    descEn: 'Peer review for course delivery performance',
    desc: 'مراجعة الزملاء لأداء المقرر الدراسي',
    icon: 'ti-users',
    iconClass: 'ic-coral',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'field-experience',
    title: 'Field Experience Specification & Report',
    titleAr: 'توصيف وتقرير الخبرة الميدانية',
    descEn: 'Field training requirements, assessment, follow-up, and reporting',
    desc: 'متطلبات التدريب الميداني وآليات التقييم والمتابعة والتقرير',
    icon: 'ti-briefcase',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'student-work-samples',
    title: 'Student Work Samples',
    titleAr: 'عينات أعمال الطلاب',
    descEn: 'Selected student work samples and evidence for course achievement',
    desc: 'عينات من أعمال الطلاب وشواهد تحقق نواتج المقرر',
    icon: 'ti-files',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
];

export const programReportTypes = [
  {
    id: 'program-specification',
    title: 'Program Specification',
    titleAr: 'توصيف البرنامج',
    descEn: 'Academic program description, objectives, and learning outcomes',
    desc: 'وصف البرنامج الأكاديمي، الأهداف، ومخرجات التعلم',
    icon: 'ti-file-certificate',
    iconClass: 'ic-amber',
    highlight: 'hl-amber',
    badge: { label: 'Pending', cls: 'b-amber' },
    defaultStatus: 's-pending',
    defaultStatusLabel: 'Pending Submit',
    category: 'main',
  },
  {
    id: 'program-report',
    title: 'Program Report',
    titleAr: 'تقرير البرنامج',
    descEn: 'Annual program performance and outcome results report',
    desc: 'تقرير أداء البرنامج ونتائج المخرجات السنوية',
    icon: 'ti-chart-line',
    iconClass: 'ic-primary',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'program-self-study',
    title: 'Self Study',
    titleAr: 'الدراسة الذاتية',
    descEn: 'Comprehensive self-study for academic program evaluation',
    desc: 'الدراسة الذاتية الشاملة لتقييم البرنامج الأكاديمي',
    icon: 'ti-microscope',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'kpis',
    title: 'KPIs & Indicators',
    titleAr: 'مؤشرات الأداء',
    descEn: 'Key performance indicators and program quality measures',
    desc: 'مؤشرات الأداء الرئيسية وقياس جودة البرنامج',
    icon: 'ti-target',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-inprogress',
    defaultStatusLabel: 'In Progress',
    category: 'additional',
  },
  {
    id: 'stakeholder-survey',
    title: 'Stakeholder Survey',
    titleAr: 'استبيان أصحاب المصلحة',
    descEn: 'Survey for stakeholders and labor market feedback',
    desc: 'استبيان أصحاب المصلحة وسوق العمل',
    icon: 'ti-users-group',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-done',
    defaultStatusLabel: 'Approved',
    category: 'additional',
  },
  {
    id: 'accreditation',
    title: 'Accreditation Evidence',
    titleAr: 'أدلة الاعتماد',
    descEn: 'Academic accreditation evidence and supporting documents',
    desc: 'أدلة ووثائق الاعتماد الأكاديمي',
    icon: 'ti-medal',
    iconClass: 'ic-coral',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'program-evidence-folder',
    title: 'Self-Study Evidence Folder',
    titleAr: 'الأدلة والشواهد الخاصة بتقرير الدراسة الذاتية',
    descEn: 'Supporting attachments and evidence for the program self-study report',
    desc: 'كل المرفقات والشواهد الداعمة لتقرير الدراسة الذاتية',
    icon: 'ti-folders',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'program-guide',
    title: 'Program Guide',
    titleAr: 'الدليل التعريفي للبرنامج',
    descEn: 'Admission, study plan, rights, duties, complaints, and student services',
    desc: 'القبول والخطة والحقوق والواجبات والشكاوى والخدمات',
    icon: 'ti-book-2',
    iconClass: 'ic-primary',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'field-training-guide',
    title: 'Field Training Guide',
    titleAr: 'دليل التدريب الميداني/التعاوني',
    descEn: 'Training skills, partners, requirements, assessment, and follow-up',
    desc: 'مهارات التدريب والجهات والشروط والتقييم وآلية المتابعة',
    icon: 'ti-briefcase',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'quality-system-guide',
    title: 'Program Quality System Guide',
    titleAr: 'دليل نظام الجودة بالبرنامج',
    descEn: 'Quality structure, committees, measurement tools, and improvement cycle',
    desc: 'الهيكل التنظيمي للجودة واللجان وأدوات القياس والتحسين',
    icon: 'ti-settings-check',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'program-course-change-policy',
    title: 'Program & Course Approval Procedures',
    titleAr: 'سياسات وإجراءات إقرار وتعديل البرنامج والمقررات',
    descEn: 'Workflow, forms, approvals, authorities, and meeting minutes',
    desc: 'مسار العمل والنماذج والصلاحيات ومحاضر الإقرار والتعديل',
    icon: 'ti-arrows-exchange',
    iconClass: 'ic-amber',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'program-improvement-plan',
    title: 'Program Improvement Plan',
    titleAr: 'خطة تحسين البرنامج',
    descEn: 'Improvement plan linked to reports, measurements, and surveys',
    desc: 'خطة تحسين مبنية على التقارير والقياسات والاستبيانات',
    icon: 'ti-progress-check',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-inprogress',
    defaultStatusLabel: 'In Progress',
    category: 'additional',
  },
  {
    id: 'advisory-committee',
    title: 'Program Advisory Committee',
    titleAr: 'اللجنة الاستشارية للبرنامج',
    descEn: 'Committee decision, minutes, recommendations, and impact evidence',
    desc: 'قرار التشكيل والمحاضر والتوصيات وأثرها على البرنامج',
    icon: 'ti-users-group',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'independent-evaluator',
    title: 'Independent Evaluator Report',
    titleAr: 'تقرير المقيم المستقل',
    descEn: 'External evaluator findings, recommendations, and improvement points',
    desc: 'تقييم خارجي شامل وتوصيات ونقاط تحسين',
    icon: 'ti-user-check',
    iconClass: 'ic-coral',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'plo-assessment-plan',
    title: 'PLO Assessment Plan',
    titleAr: 'خطة قياس نواتج التعلم للبرنامج',
    descEn: 'PLO measurement plan, tools, schedule, and responsibilities',
    desc: 'خطة قياس مخرجات التعلم وأدوات القياس ودوريتها',
    icon: 'ti-route',
    iconClass: 'ic-primary',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'plo-assessment-report',
    title: 'PLO Assessment Report',
    titleAr: 'تقرير قياس جميع نواتج التعلم',
    descEn: 'Actual assessment results for all program learning outcomes',
    desc: 'نتائج القياس الفعلية لجميع مخرجات تعلم البرنامج',
    icon: 'ti-chart-dots',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'learning-outcomes-verification',
    title: 'Learning Outcomes Verification',
    titleAr: 'نموذج التحقق من قياس نواتج التعلم',
    descEn: 'Verification and validation of the learning outcomes assessment cycle',
    desc: 'التحقق من عملية قياس مخرجات التعلم واعتمادها',
    icon: 'ti-checkup-list',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'nqf-alignment',
    title: 'NQF Alignment Report',
    titleAr: 'تقرير الاتساق مع الإطار الوطني للمؤهلات',
    descEn: 'Program mapping and consistency with the National Qualifications Framework',
    desc: 'مواءمة البرنامج مع الإطار الوطني للمؤهلات',
    icon: 'ti-git-merge',
    iconClass: 'ic-amber',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'specialized-standards-alignment',
    title: 'Specialized Standards Alignment',
    titleAr: 'تقرير الاتساق مع المعايير الأكاديمية التخصصية',
    descEn: 'Mapping the program against specialized academic standards',
    desc: 'مواءمة البرنامج مع المعايير الأكاديمية التخصصية',
    icon: 'ti-adjustments-check',
    iconClass: 'ic-coral',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'faculty-list',
    title: 'Faculty Members List',
    titleAr: 'قائمة أعضاء هيئة التدريس',
    descEn: 'Faculty details, assignments, qualifications, and courses',
    desc: 'بيانات أعضاء هيئة التدريس والمقررات والمهام والمؤهلات',
    icon: 'ti-id',
    iconClass: 'ic-primary',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'faculty-cvs',
    title: 'Faculty CVs',
    titleAr: 'السير الذاتية لأعضاء هيئة التدريس',
    descEn: 'Updated CVs for all faculty members in the program',
    desc: 'سير ذاتية محدثة لجميع أعضاء هيئة التدريس بالبرنامج',
    icon: 'ti-file-cv',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
];

export const institutionalReportTypes = [
  {
    id: 'ia-application-form',
    title: 'Institutional Accreditation Application Form',
    titleAr: 'نموذج التقدم للاعتماد المؤسسي',
    descEn: 'Institutional application package for accreditation submission',
    desc: 'نموذج وبيانات التقدم للاعتماد المؤسسي',
    icon: 'ti-file-description',
    iconClass: 'ic-primary',
    highlight: 'hl-primary',
    badge: { label: 'Pending', cls: 'b-primary' },
    defaultStatus: 's-pending',
    defaultStatusLabel: 'Pending Submit',
    category: 'main',
  },
  {
    id: 'ia-review-visit-documents',
    title: 'Required Documents for Review Visit',
    titleAr: 'الوثائق المطلوبة لزيارة المراجعة',
    descEn: 'Documents required before and during the institutional review visit',
    desc: 'الوثائق المطلوبة قبل وأثناء زيارة المراجعة',
    icon: 'ti-folders',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'ia-recommendations-response',
    title: 'Response to Accreditation Recommendations and Information Errors',
    titleAr: 'استجابة المؤسسات نحو توصيات الاعتماد والأخطاء المعلوماتية',
    descEn: 'Institutional response to recommendations and information corrections',
    desc: 'استجابة المؤسسة لتوصيات الاعتماد وتصحيح الأخطاء المعلوماتية',
    icon: 'ti-message-report',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'ia-standards',
    title: 'Accreditation Standards for Higher Education Institutions',
    titleAr: 'معايير الاعتماد لمؤسسات التعليم العالي',
    descEn: 'Institutional accreditation standards and compliance evidence',
    desc: 'معايير الاعتماد المؤسسي وشواهد الاستيفاء',
    icon: 'ti-certificate',
    iconClass: 'ic-amber',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'ia-kpis',
    title: 'Key Performance Indicators for Higher Education Institutions',
    titleAr: 'مؤشرات الأداء الرئيسية لمؤسسات التعليم العالي',
    descEn: 'Institutional KPIs, trends, measures, and evidence',
    desc: 'مؤشرات الأداء المؤسسية والقياسات والاتجاهات والشواهد',
    icon: 'ti-target',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-inprogress',
    defaultStatusLabel: 'In Progress',
    category: 'main',
  },
  {
    id: 'ia-improvement-plan',
    title: 'Improvement Plan for Accreditation Recommendations',
    titleAr: 'خطة التحسين لتوصيات الاعتماد',
    descEn: 'Improvement plan responding to accreditation recommendations',
    desc: 'خطة التحسين المرتبطة بتوصيات الاعتماد',
    icon: 'ti-progress-check',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'ia-eligibility-report',
    title: 'Institutional Accreditation Eligibility Fulfillment Report',
    titleAr: 'تقرير استيفاء شروط الاعتماد المؤسسي',
    descEn: 'Report on fulfilling institutional accreditation eligibility requirements',
    desc: 'تقرير استيفاء شروط ومتطلبات الاعتماد المؤسسي',
    icon: 'ti-clipboard-check',
    iconClass: 'ic-primary',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'ia-basic-data-followup',
    title: 'Basic Data and Performance Indicators Form - Follow-up',
    titleAr: 'نموذج البيانات الأساسية ومؤشرات الأداء للمؤسسات المعتمدة - المتابعة',
    descEn: 'Basic data and performance indicator follow-up form',
    desc: 'نموذج المتابعة للبيانات الأساسية ومؤشرات الأداء',
    icon: 'ti-list-details',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'ia-self-study',
    title: 'Institutional Self-Study Report',
    titleAr: 'تقرير الدراسة الذاتية للمؤسسة',
    descEn: 'Institutional self-study report against accreditation standards',
    desc: 'تقرير الدراسة الذاتية للمؤسسة مقابل معايير الاعتماد',
    icon: 'ti-microscope',
    iconClass: 'ic-amber',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'ia-periodic-followup',
    title: 'Periodic Follow-up Report for Accredited Institutions',
    titleAr: 'تقرير المتابعة الدورية للمؤسسات المعتمدة',
    descEn: 'Periodic follow-up report for accredited institutions',
    desc: 'تقرير المتابعة الدورية للمؤسسات المعتمدة',
    icon: 'ti-calendar-stats',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'ia-substantial-changes',
    title: 'Substantial Changes Report for Accredited Institutions',
    titleAr: 'تقرير التغيرات الجوهرية للمؤسسات المعتمدة',
    descEn: 'Report substantial institutional changes after accreditation',
    desc: 'تقرير التغيرات الجوهرية للمؤسسات المعتمدة',
    icon: 'ti-arrows-exchange',
    iconClass: 'ic-coral',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
];

export const historyItems = [
  { year: '2024/2025', date: 'Submitted 14 Jan 2025', status: 's-pending', statusLabel: 'Pending Submit', action: 'view' },
  { year: '2023/2024', date: 'Approved 8 Feb 2024',   status: 's-done',    statusLabel: 'Approved',       action: 'view' },
  { year: '2022/2023', date: 'Archived',               status: 's-archived',statusLabel: 'Archived',       action: 'view' },
];

const baseCrnApprovals = [
  { username: 'Mohamed Helal', job: 'Instructor', status: 'Submit', reason: '', date: '5/12/26, 12:32 PM' },
  { username: 'coordinator coordinator', job: 'Coordinator', status: 'Approve', reason: '', date: '5/12/26, 12:35 PM' },
  { username: 'QualityAssistant qualityAssistant', job: 'Quality Assistant', status: 'Approve', reason: '', date: '5/12/26, 12:37 PM' },
];

export const courseCrnReportDetails = {
  'crn-cs12-1': {
    submittedAt: '2026-05-12T12:37:00',
    academicYear: '2026-2027',
    semester: 'First Semester',
    location: 'Main Campus',
    noOfStudentsStarting: 40,
    noOfStudentsCompleting: 35,
    topicsNotCovered: [
      {
        topic: 'Introduction to databases and data management',
        reason: 'One lab session was replaced by the midterm review and advising period.',
        impact: 'Low impact; core concepts were covered through readings and examples.',
        action: 'Add a supervised database lab in week 13 and include a short LMS activity.',
      },
      {
        topic: 'Advanced internet protocols overview',
        reason: 'Course pacing prioritized problem-solving workshops for first-year students.',
        impact: 'No effect on core CLO achievement; topic is enrichment for this level.',
        action: 'Move the overview to a recorded micro-lecture with a formative quiz.',
      },
    ],
    grades: { 'A+': 3, A: 4, 'B+': 6, B: 8, 'C+': 9, C: 8, 'D+': 6, D: 7, F: 7 },
    statusDistribution: { 'Denied Entry': 0, 'In Progress': 0, Incomplete: 0, Pass: 35, Fail: 7, Withdrawn: 4, Withdraw: 4 },
    resultsComment: 'Most students met the expected foundation level. More practice is needed on data representation and basic network concepts.',
    outcomes: [
      { group: 'Knowledge and Understanding', clo: 'Explain fundamental computing concepts and terminology.', plo: 'PLO1', assessment: 'Exit Exam', targetLevel: 70, actualLevel: 76, comment: 'Target met; students showed solid understanding of computing vocabulary and concepts.' },
      { group: 'Skills', clo: 'Apply structured problem-solving steps to simple computing tasks.', plo: 'PLO2', assessment: 'Practical lab assessment', targetLevel: 70, actualLevel: 72, comment: 'Target met with a small margin; more guided lab drills are recommended.' },
      { group: 'Values', clo: 'Demonstrate responsibility, collaboration, and ethical use of computing resources.', plo: 'PLO3', assessment: 'Peer and alumni survey', targetLevel: 75, actualLevel: 78, comment: 'Students participated well in group activities and followed lab conduct expectations.' },
    ],
    cloRecommendation: 'Keep the current assessment mix and add early diagnostic exercises for problem solving before week 4.',
    improvementPlans: [
      { recommendation: 'Increase formative practice for data representation and networking basics.', action: 'Publish weekly auto-graded quizzes with immediate feedback.', support: 'LMS question bank support from the quality unit.' },
      { recommendation: 'Strengthen practical problem-solving confidence before the final exam.', action: 'Add two supervised lab review sessions before week 14.', support: 'Lab availability and teaching assistant coverage.' },
    ],
    improvementActions: [
      { action: 'Weekly auto-graded quiz package', achievement: 80, comments: 'Question bank created for six topics; remaining topics scheduled for next offering.' },
      { action: 'Additional lab review sessions', achievement: 70, comments: 'One session completed and the second added to the next delivery plan.' },
    ],
    overallComment: 'The CRN is approved. Improvement actions should focus on early practice and documented lab support.',
    approvals: baseCrnApprovals,
  },
  'crn-cs12-ds-clo': {
    submittedAt: '2026-05-12T12:42:00',
    academicYear: '2026-2027',
    semester: 'First Semester',
    location: 'Main Campus',
    noOfStudentsStarting: 38,
    noOfStudentsCompleting: 34,
    topicsNotCovered: [
      { topic: 'Introduction to databases and data management', reason: 'Lab equipment maintenance reduced available practical time.', impact: 'Moderate impact on hands-on confidence, with theory still covered.', action: 'Schedule one make-up lab and add a recorded walkthrough.' },
    ],
    grades: { 'A+': 2, A: 5, 'B+': 7, B: 8, 'C+': 8, C: 6, 'D+': 4, D: 3, F: 2 },
    statusDistribution: { 'Denied Entry': 0, 'In Progress': 0, Incomplete: 1, Pass: 34, Fail: 2, Withdrawn: 2, Withdraw: 2 },
    resultsComment: 'The section achieved the main CLO targets, with practical lab continuity identified as the main improvement area.',
    outcomes: [
      { group: 'Knowledge and Understanding', clo: 'Explain fundamental computing concepts and terminology.', plo: 'PLO1', assessment: 'Exit Exam', targetLevel: 70, actualLevel: 74, comment: 'Target achieved.' },
      { group: 'Skills', clo: 'Apply structured problem-solving steps to simple computing tasks.', plo: 'PLO2', assessment: 'Lab performance', targetLevel: 70, actualLevel: 71, comment: 'Target achieved with limited margin.' },
      { group: 'Values', clo: 'Demonstrate responsibility, collaboration, and ethical use of computing resources.', plo: 'PLO3', assessment: 'Group activity rubric', targetLevel: 75, actualLevel: 77, comment: 'Target achieved.' },
    ],
    cloRecommendation: 'Protect scheduled lab time and prepare fallback online exercises for any cancelled lab.',
    improvementPlans: [
      { recommendation: 'Reduce impact of lab interruptions.', action: 'Prepare online backup labs for each practical topic.', support: 'Instructional technology support.' },
    ],
    improvementActions: [
      { action: 'Online backup lab templates', achievement: 60, comments: 'Templates started for three topics.' },
    ],
    overallComment: 'Approved with follow-up on backup lab readiness.',
    approvals: baseCrnApprovals,
  },
  'crn-it1231-1': {
    submittedAt: '2026-05-13T09:20:00',
    academicYear: '2026-2027',
    semester: 'First Semester',
    location: 'Main Campus',
    noOfStudentsStarting: 42,
    noOfStudentsCompleting: 39,
    topicsNotCovered: [],
    grades: { 'A+': 4, A: 6, 'B+': 8, B: 9, 'C+': 7, C: 6, 'D+': 3, D: 2, F: 1 },
    statusDistribution: { 'Denied Entry': 0, 'In Progress': 0, Incomplete: 0, Pass: 39, Fail: 1, Withdrawn: 2, Withdraw: 2 },
    resultsComment: 'Student achievement is aligned with the course target, especially in IT infrastructure and applications topics.',
    outcomes: [
      { group: 'Knowledge and Understanding', clo: 'Identify major IT components and services.', plo: 'PLO1', assessment: 'Exit Exam', targetLevel: 70, actualLevel: 79, comment: 'Target achieved.' },
      { group: 'Skills', clo: 'Use common productivity and network concepts.', plo: 'PLO2', assessment: 'Practical task', targetLevel: 70, actualLevel: 75, comment: 'Target achieved.' },
      { group: 'Values', clo: 'Explain responsible use of information systems.', plo: 'PLO3', assessment: 'Participation rubric', targetLevel: 75, actualLevel: 80, comment: 'Target achieved.' },
    ],
    cloRecommendation: 'Continue using practical IT scenarios and add one cybersecurity awareness case study.',
    improvementPlans: [
      { recommendation: 'Strengthen cybersecurity awareness.', action: 'Add a case study to week 8.', support: 'Cybersecurity faculty reviewer.' },
    ],
    improvementActions: [
      { action: 'Cybersecurity case study', achievement: 50, comments: 'Draft case prepared for review.' },
    ],
    overallComment: 'Approved with one enhancement for the next delivery.',
    approvals: baseCrnApprovals,
  },
  'crn-it1231-2': {
    submittedAt: '2026-05-13T10:05:00',
    academicYear: '2026-2027',
    semester: 'First Semester',
    location: 'Branch',
    noOfStudentsStarting: 36,
    noOfStudentsCompleting: 33,
    topicsNotCovered: [],
    grades: { 'A+': 3, A: 4, 'B+': 6, B: 8, 'C+': 7, C: 5, 'D+': 4, D: 2, F: 2 },
    statusDistribution: { 'Denied Entry': 0, 'In Progress': 0, Incomplete: 0, Pass: 33, Fail: 2, Withdrawn: 1, Withdraw: 1 },
    resultsComment: 'Achievement is acceptable, with branch students requesting more guided lab examples.',
    outcomes: [
      { group: 'Knowledge and Understanding', clo: 'Identify major IT components and services.', plo: 'PLO1', assessment: 'Exit Exam', targetLevel: 70, actualLevel: 73, comment: 'Target achieved.' },
      { group: 'Skills', clo: 'Use common productivity and network concepts.', plo: 'PLO2', assessment: 'Practical task', targetLevel: 70, actualLevel: 71, comment: 'Target achieved with limited margin.' },
      { group: 'Values', clo: 'Explain responsible use of information systems.', plo: 'PLO3', assessment: 'Participation rubric', targetLevel: 75, actualLevel: 76, comment: 'Target achieved.' },
    ],
    cloRecommendation: 'Add branch-specific lab office hours before practical assessments.',
    improvementPlans: [
      { recommendation: 'Improve practical confidence at branch delivery.', action: 'Schedule remote lab office hours.', support: 'Virtual lab access.' },
    ],
    improvementActions: [
      { action: 'Remote lab office hours', achievement: 45, comments: 'Schedule drafted for next semester.' },
    ],
    overallComment: 'Approved with action required for practical support.',
    approvals: baseCrnApprovals,
  },
  'crn-c180-1': {
    submittedAt: '2026-05-14T11:10:00',
    academicYear: '2026-2027',
    semester: 'First Semester',
    location: 'Main Campus',
    noOfStudentsStarting: 44,
    noOfStudentsCompleting: 41,
    topicsNotCovered: [
      { topic: 'Functions, arrays, and debugging practice', reason: 'Additional time was used for control structures remediation.', impact: 'Moderate impact on advanced practice readiness.', action: 'Add two focused debugging labs in the next offering.' },
    ],
    grades: { 'A+': 2, A: 5, 'B+': 8, B: 10, 'C+': 8, C: 6, 'D+': 5, D: 3, F: 4 },
    statusDistribution: { 'Denied Entry': 0, 'In Progress': 0, Incomplete: 0, Pass: 41, Fail: 4, Withdrawn: 3, Withdraw: 3 },
    resultsComment: 'Students performed well in algorithms and basic control structures, while functions and debugging need reinforcement.',
    outcomes: [
      { group: 'Knowledge and Understanding', clo: 'Describe basic programming constructs.', plo: 'PLO1', assessment: 'Midterm and final exam', targetLevel: 70, actualLevel: 74, comment: 'Target achieved.' },
      { group: 'Skills', clo: 'Implement basic programs and test code.', plo: 'PLO2', assessment: 'Programming lab', targetLevel: 70, actualLevel: 69, comment: 'Below target by one point; improvement plan required.' },
      { group: 'Values', clo: 'Demonstrate academic integrity in coding tasks.', plo: 'PLO3', assessment: 'Lab conduct rubric', targetLevel: 75, actualLevel: 78, comment: 'Target achieved.' },
    ],
    cloRecommendation: 'Increase supervised coding drills for functions and debugging.',
    improvementPlans: [
      { recommendation: 'Raise skills CLO achievement above target.', action: 'Add weekly coding drill sheets and live debugging demonstrations.', support: 'Teaching assistant and lab reservation.' },
    ],
    improvementActions: [
      { action: 'Coding drill sheets', achievement: 65, comments: 'Four drill sheets drafted.' },
    ],
    overallComment: 'Approved with skills CLO improvement follow-up.',
    approvals: baseCrnApprovals,
  },
  'crn-c180-ds-clo': {
    submittedAt: '2026-05-14T11:18:00',
    academicYear: '2026-2027',
    semester: 'First Semester',
    location: 'Main Campus',
    noOfStudentsStarting: 40,
    noOfStudentsCompleting: 37,
    topicsNotCovered: [],
    grades: { 'A+': 3, A: 6, 'B+': 7, B: 8, 'C+': 7, C: 5, 'D+': 3, D: 2, F: 2 },
    statusDistribution: { 'Denied Entry': 0, 'In Progress': 0, Incomplete: 0, Pass: 37, Fail: 2, Withdrawn: 1, Withdraw: 1 },
    resultsComment: 'Direct CLO assessment shows acceptable achievement with a need for more debugging examples.',
    outcomes: [
      { group: 'Knowledge and Understanding', clo: 'Describe basic programming constructs.', plo: 'PLO1', assessment: 'Direct CLO exam items', targetLevel: 70, actualLevel: 76, comment: 'Target achieved.' },
      { group: 'Skills', clo: 'Implement basic programs and test code.', plo: 'PLO2', assessment: 'Direct lab rubric', targetLevel: 70, actualLevel: 72, comment: 'Target achieved.' },
      { group: 'Values', clo: 'Demonstrate academic integrity in coding tasks.', plo: 'PLO3', assessment: 'Lab conduct rubric', targetLevel: 75, actualLevel: 79, comment: 'Target achieved.' },
    ],
    cloRecommendation: 'Keep direct CLO assessment and add one debugging practice checkpoint.',
    improvementPlans: [
      { recommendation: 'Improve debugging evidence.', action: 'Add a marked debugging checkpoint.', support: 'Lab instructor review.' },
    ],
    improvementActions: [
      { action: 'Debugging checkpoint design', achievement: 55, comments: 'Rubric draft completed.' },
    ],
    overallComment: 'Approved with minor enhancement.',
    approvals: baseCrnApprovals,
  },
};

export const courseCrnSubmissions = {
  cs12: {
    courseCode: 'CS12',
    courseTitle: 'Computer Science Fundamentals',
    courseTitleAr: 'أساسيات علوم الحاسب',
    term: 'First Semester',
    termAr: 'الفصل الدراسي الأول',
    coordinator: 'Mohamed Ali Mohamed Helal',
    submissions: [
      {
        id: 'crn-cs12-1',
        crn: '1',
        title: 'First Semester',
        titleAr: 'الفصل الدراسي الأول',
        instructor: 'Mohamed Ali Mohamed Helal',
        status: 'Approved',
        statusAr: 'معتمد',
      },
      {
        id: 'crn-cs12-ds-clo',
        crn: 'DS CLO',
        title: 'First Semester',
        titleAr: 'الفصل الدراسي الأول',
        instructor: 'Mohamed Ali Mohamed Helal',
        status: 'Approved',
        statusAr: 'معتمد',
      },
    ],
  },
  it1231: {
    courseCode: 'IT1231',
    courseTitle: 'Information Technology Fundamentals',
    courseTitleAr: 'أساسيات تقنية المعلومات',
    term: 'First Semester',
    termAr: 'الفصل الدراسي الأول',
    coordinator: 'Mohamed Ali Mohamed Helal',
    submissions: [
      { id: 'crn-it1231-1', crn: '1', title: 'First Semester', titleAr: 'الفصل الدراسي الأول', instructor: 'Mohamed Ali Mohamed Helal', status: 'Approved', statusAr: 'معتمد' },
      { id: 'crn-it1231-2', crn: '2', title: 'First Semester', titleAr: 'الفصل الدراسي الأول', instructor: 'Mohamed Ali Mohamed Helal', status: 'Approved', statusAr: 'معتمد' },
    ],
  },
  c180: {
    courseCode: 'C180',
    courseTitle: 'Programming Basic',
    courseTitleAr: 'أساسيات البرمجة',
    term: 'First Semester',
    termAr: 'الفصل الدراسي الأول',
    coordinator: 'Mohamed Ali Mohamed Helal',
    submissions: [
      { id: 'crn-c180-1', crn: '1', title: 'First Semester', titleAr: 'الفصل الدراسي الأول', instructor: 'Mohamed Ali Mohamed Helal', status: 'Approved', statusAr: 'معتمد' },
      { id: 'crn-c180-ds-clo', crn: 'DS CLO', title: 'First Semester', titleAr: 'الفصل الدراسي الأول', instructor: 'Mohamed Ali Mohamed Helal', status: 'Approved', statusAr: 'معتمد' },
    ],
  },
};
