export const courses = [
  { id: 'cs12',   code: 'CS12',   name: 'Computer Science Fundamentals',      semester: 'First Semester' },
  { id: 'it1231', code: 'IT1231', name: 'Information Technology Fundamentals', semester: 'First Semester' },
  { id: 'c180',   code: 'C180',   name: 'Programming Basic',                   semester: 'First Semester' },
];

export const programs = [
  { id: 'cs', code: 'CS', name: 'Computer Science',        year: '2025/2026' },
  { id: 'it', code: 'IT', name: 'Information Technology',  year: '2025/2026' },
  { id: 'se', code: 'SE', name: 'Software Engineering',     year: '2025/2026' },
];

export const courseReportTypes = [
  {
    id: 'course-specification',
    title: 'Course Specification',
    desc: 'تفاصيل المقرر، الأهداف، والمحتوى الدراسي',
    icon: 'ti-file-description',
    iconClass: 'ic-blue',
    highlight: 'hl-blue',
    badge: { label: 'Pending', cls: 'b-blue' },
    defaultStatus: 's-pending',
    defaultStatusLabel: 'Pending Submit',
    category: 'main',
  },
  {
    id: 'crns',
    title: 'CRNs',
    desc: 'أرقام تسجيل الأقسام والشعب الدراسية',
    icon: 'ti-list-numbers',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'course-report',
    title: 'Course Report',
    desc: 'تقرير نتائج المقرر ومستوى التحصيل',
    icon: 'ti-chart-bar',
    iconClass: 'ic-amber',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'course-portfolio',
    title: 'Course Portfolio',
    desc: 'ملف المقرر الشامل والمستندات المرفقة',
    icon: 'ti-folders',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'student-survey',
    title: 'Student Survey',
    desc: 'استبيان رأي الطلاب في المقرر والتدريس',
    icon: 'ti-message-circle',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-done',
    defaultStatusLabel: 'Approved',
    category: 'additional',
  },
  {
    id: 'peer-review',
    title: 'Peer Review',
    desc: 'مراجعة الزملاء لأداء المقرر الدراسي',
    icon: 'ti-users',
    iconClass: 'ic-coral',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
];

export const programReportTypes = [
  {
    id: 'program-specification',
    title: 'Program Specification',
    desc: 'وصف البرنامج الأكاديمي، الأهداف، ومخرجات التعلم',
    icon: 'ti-file-certificate',
    iconClass: 'ic-amber',
    highlight: 'hl-amber',
    badge: { label: 'Pending', cls: 'b-amber' },
    defaultStatus: 's-pending',
    defaultStatusLabel: 'Pending Submit',
    category: 'main',
  },
  {
    id: 'program-report',
    title: 'Program Report',
    desc: 'تقرير أداء البرنامج ونتائج المخرجات السنوية',
    icon: 'ti-chart-line',
    iconClass: 'ic-blue',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'program-self-study',
    title: 'Program Self Study',
    desc: 'الدراسة الذاتية الشاملة لتقييم البرنامج الأكاديمي',
    icon: 'ti-microscope',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'kpis',
    title: 'KPIs & Indicators',
    desc: 'مؤشرات الأداء الرئيسية وقياس جودة البرنامج',
    icon: 'ti-target',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-inprogress',
    defaultStatusLabel: 'In Progress',
    category: 'additional',
  },
  {
    id: 'stakeholder-survey',
    title: 'Stakeholder Survey',
    desc: 'استبيان أصحاب المصلحة وسوق العمل',
    icon: 'ti-users-group',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-done',
    defaultStatusLabel: 'Approved',
    category: 'additional',
  },
  {
    id: 'accreditation',
    title: 'Accreditation Evidence',
    desc: 'أدلة ووثائق الاعتماد الأكاديمي',
    icon: 'ti-medal',
    iconClass: 'ic-coral',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
];

export const historyItems = [
  { year: '2024/2025', date: 'Submitted 14 Jan 2025', status: 's-pending', statusLabel: 'Pending Submit', action: 'view' },
  { year: '2023/2024', date: 'Approved 8 Feb 2024',   status: 's-done',    statusLabel: 'Approved',       action: 'view' },
  { year: '2022/2023', date: 'Archived',               status: 's-archived',statusLabel: 'Archived',       action: 'view' },
];
