export const courses = [
  { id: 'cs12',   code: 'CS12',   name: 'Computer Science Fundamentals',      nameAr: 'أساسيات علوم الحاسب',          semester: 'First Semester', semesterAr: 'الفصل الدراسي الأول' },
  { id: 'it1231', code: 'IT1231', name: 'Information Technology Fundamentals', nameAr: 'أساسيات تقنية المعلومات',      semester: 'First Semester', semesterAr: 'الفصل الدراسي الأول' },
  { id: 'c180',   code: 'C180',   name: 'Programming Basic',                   nameAr: 'أساسيات البرمجة',              semester: 'First Semester', semesterAr: 'الفصل الدراسي الأول' },
];

export const programs = [
  { id: 'cs', code: 'CS', name: 'Computer Science',        nameAr: 'علوم الحاسب',       year: '2025/2026' },
  { id: 'it', code: 'IT', name: 'Information Technology',  nameAr: 'تقنية المعلومات',   year: '2025/2026' },
  { id: 'se', code: 'SE', name: 'Software Engineering',    nameAr: 'هندسة البرمجيات',    year: '2025/2026' },
];

export const courseReportTypes = [
  {
    id: 'course-specification',
    title: 'Course Specification',
    titleAr: 'توصيف المقرر',
    descEn: 'Course details, objectives, and teaching content',
    desc: 'تفاصيل المقرر، الأهداف، والمحتوى الدراسي',
    icon: 'ti-file-description',
    iconClass: 'ic-primary',
    highlight: 'hl-primary',
    badge: { label: 'Pending', cls: 'b-primary' },
    defaultStatus: 's-pending',
    defaultStatusLabel: 'Pending Submit',
    category: 'main',
  },
  {
    id: 'crns',
    title: 'CRNs',
    titleAr: 'أرقام الشعب',
    descEn: 'Registration numbers for sections and course groups',
    desc: 'أرقام تسجيل الأقسام والشعب الدراسية',
    icon: 'ti-list-numbers',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'course-report',
    title: 'Course Report',
    titleAr: 'تقرير المقرر',
    descEn: 'Course results and achievement level report',
    desc: 'تقرير نتائج المقرر ومستوى التحصيل',
    icon: 'ti-chart-bar',
    iconClass: 'ic-amber',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'course-portfolio',
    title: 'Course Portfolio',
    titleAr: 'ملف المقرر',
    descEn: 'Complete course portfolio and attached documents',
    desc: 'ملف المقرر الشامل والمستندات المرفقة',
    icon: 'ti-folders',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'student-survey',
    title: 'Student Survey',
    titleAr: 'استبيان الطلاب',
    descEn: 'Student feedback survey for the course and teaching',
    desc: 'استبيان رأي الطلاب في المقرر والتدريس',
    icon: 'ti-message-circle',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-done',
    defaultStatusLabel: 'Approved',
    category: 'additional',
  },
  {
    id: 'peer-review',
    title: 'Peer Review',
    titleAr: 'مراجعة النظراء',
    descEn: 'Peer review for course delivery performance',
    desc: 'مراجعة الزملاء لأداء المقرر الدراسي',
    icon: 'ti-users',
    iconClass: 'ic-coral',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'field-experience',
    title: 'Field Experience Specification & Report',
    titleAr: 'توصيف وتقرير الخبرة الميدانية',
    descEn: 'Field training requirements, assessment, follow-up, and reporting',
    desc: 'متطلبات التدريب الميداني وآليات التقييم والمتابعة والتقرير',
    icon: 'ti-briefcase',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'student-work-samples',
    title: 'Student Work Samples',
    titleAr: 'عينات أعمال الطلاب',
    descEn: 'Selected student work samples and evidence for course achievement',
    desc: 'عينات من أعمال الطلاب وشواهد تحقق نواتج المقرر',
    icon: 'ti-files',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
];

export const programReportTypes = [
  {
    id: 'program-specification',
    title: 'Program Specification',
    titleAr: 'توصيف البرنامج',
    descEn: 'Academic program description, objectives, and learning outcomes',
    desc: 'وصف البرنامج الأكاديمي، الأهداف، ومخرجات التعلم',
    icon: 'ti-file-certificate',
    iconClass: 'ic-amber',
    highlight: 'hl-amber',
    badge: { label: 'Pending', cls: 'b-amber' },
    defaultStatus: 's-pending',
    defaultStatusLabel: 'Pending Submit',
    category: 'main',
  },
  {
    id: 'program-report',
    title: 'Program Report',
    titleAr: 'تقرير البرنامج',
    descEn: 'Annual program performance and outcome results report',
    desc: 'تقرير أداء البرنامج ونتائج المخرجات السنوية',
    icon: 'ti-chart-line',
    iconClass: 'ic-primary',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'program-self-study',
    title: 'Self Study',
    titleAr: 'الدراسة الذاتية',
    descEn: 'Comprehensive self-study for academic program evaluation',
    desc: 'الدراسة الذاتية الشاملة لتقييم البرنامج الأكاديمي',
    icon: 'ti-microscope',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'kpis',
    title: 'KPIs & Indicators',
    titleAr: 'مؤشرات الأداء',
    descEn: 'Key performance indicators and program quality measures',
    desc: 'مؤشرات الأداء الرئيسية وقياس جودة البرنامج',
    icon: 'ti-target',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-inprogress',
    defaultStatusLabel: 'In Progress',
    category: 'additional',
  },
  {
    id: 'stakeholder-survey',
    title: 'Stakeholder Survey',
    titleAr: 'استبيان أصحاب المصلحة',
    descEn: 'Survey for stakeholders and labor market feedback',
    desc: 'استبيان أصحاب المصلحة وسوق العمل',
    icon: 'ti-users-group',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-done',
    defaultStatusLabel: 'Approved',
    category: 'additional',
  },
  {
    id: 'accreditation',
    title: 'Accreditation Evidence',
    titleAr: 'أدلة الاعتماد',
    descEn: 'Academic accreditation evidence and supporting documents',
    desc: 'أدلة ووثائق الاعتماد الأكاديمي',
    icon: 'ti-medal',
    iconClass: 'ic-coral',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'program-evidence-folder',
    title: 'Self-Study Evidence Folder',
    titleAr: 'الأدلة والشواهد الخاصة بتقرير الدراسة الذاتية',
    descEn: 'Supporting attachments and evidence for the program self-study report',
    desc: 'كل المرفقات والشواهد الداعمة لتقرير الدراسة الذاتية',
    icon: 'ti-folders',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'program-guide',
    title: 'Program Guide',
    titleAr: 'الدليل التعريفي للبرنامج',
    descEn: 'Admission, study plan, rights, duties, complaints, and student services',
    desc: 'القبول والخطة والحقوق والواجبات والشكاوى والخدمات',
    icon: 'ti-book-2',
    iconClass: 'ic-primary',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'field-training-guide',
    title: 'Field Training Guide',
    titleAr: 'دليل التدريب الميداني/التعاوني',
    descEn: 'Training skills, partners, requirements, assessment, and follow-up',
    desc: 'مهارات التدريب والجهات والشروط والتقييم وآلية المتابعة',
    icon: 'ti-briefcase',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'quality-system-guide',
    title: 'Program Quality System Guide',
    titleAr: 'دليل نظام الجودة بالبرنامج',
    descEn: 'Quality structure, committees, measurement tools, and improvement cycle',
    desc: 'الهيكل التنظيمي للجودة واللجان وأدوات القياس والتحسين',
    icon: 'ti-settings-check',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'program-course-change-policy',
    title: 'Program & Course Approval Procedures',
    titleAr: 'سياسات وإجراءات إقرار وتعديل البرنامج والمقررات',
    descEn: 'Workflow, forms, approvals, authorities, and meeting minutes',
    desc: 'مسار العمل والنماذج والصلاحيات ومحاضر الإقرار والتعديل',
    icon: 'ti-arrows-exchange',
    iconClass: 'ic-amber',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'program-improvement-plan',
    title: 'Program Improvement Plan',
    titleAr: 'خطة تحسين البرنامج',
    descEn: 'Improvement plan linked to reports, measurements, and surveys',
    desc: 'خطة تحسين مبنية على التقارير والقياسات والاستبيانات',
    icon: 'ti-progress-check',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-inprogress',
    defaultStatusLabel: 'In Progress',
    category: 'additional',
  },
  {
    id: 'advisory-committee',
    title: 'Program Advisory Committee',
    titleAr: 'اللجنة الاستشارية للبرنامج',
    descEn: 'Committee decision, minutes, recommendations, and impact evidence',
    desc: 'قرار التشكيل والمحاضر والتوصيات وأثرها على البرنامج',
    icon: 'ti-users-group',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'independent-evaluator',
    title: 'Independent Evaluator Report',
    titleAr: 'تقرير المقيم المستقل',
    descEn: 'External evaluator findings, recommendations, and improvement points',
    desc: 'تقييم خارجي شامل وتوصيات ونقاط تحسين',
    icon: 'ti-user-check',
    iconClass: 'ic-coral',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'plo-assessment-plan',
    title: 'PLO Assessment Plan',
    titleAr: 'خطة قياس نواتج التعلم للبرنامج',
    descEn: 'PLO measurement plan, tools, schedule, and responsibilities',
    desc: 'خطة قياس مخرجات التعلم وأدوات القياس ودوريتها',
    icon: 'ti-route',
    iconClass: 'ic-primary',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'plo-assessment-report',
    title: 'PLO Assessment Report',
    titleAr: 'تقرير قياس جميع نواتج التعلم',
    descEn: 'Actual assessment results for all program learning outcomes',
    desc: 'نتائج القياس الفعلية لجميع مخرجات تعلم البرنامج',
    icon: 'ti-chart-dots',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'learning-outcomes-verification',
    title: 'Learning Outcomes Verification',
    titleAr: 'نموذج التحقق من قياس نواتج التعلم',
    descEn: 'Verification and validation of the learning outcomes assessment cycle',
    desc: 'التحقق من عملية قياس مخرجات التعلم واعتمادها',
    icon: 'ti-checkup-list',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'nqf-alignment',
    title: 'NQF Alignment Report',
    titleAr: 'تقرير الاتساق مع الإطار الوطني للمؤهلات',
    descEn: 'Program mapping and consistency with the National Qualifications Framework',
    desc: 'مواءمة البرنامج مع الإطار الوطني للمؤهلات',
    icon: 'ti-git-merge',
    iconClass: 'ic-amber',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'specialized-standards-alignment',
    title: 'Specialized Standards Alignment',
    titleAr: 'تقرير الاتساق مع المعايير الأكاديمية التخصصية',
    descEn: 'Mapping the program against specialized academic standards',
    desc: 'مواءمة البرنامج مع المعايير الأكاديمية التخصصية',
    icon: 'ti-adjustments-check',
    iconClass: 'ic-coral',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'faculty-list',
    title: 'Faculty Members List',
    titleAr: 'قائمة أعضاء هيئة التدريس',
    descEn: 'Faculty details, assignments, qualifications, and courses',
    desc: 'بيانات أعضاء هيئة التدريس والمقررات والمهام والمؤهلات',
    icon: 'ti-id',
    iconClass: 'ic-primary',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'faculty-cvs',
    title: 'Faculty CVs',
    titleAr: 'السير الذاتية لأعضاء هيئة التدريس',
    descEn: 'Updated CVs for all faculty members in the program',
    desc: 'سير ذاتية محدثة لجميع أعضاء هيئة التدريس بالبرنامج',
    icon: 'ti-file-cv',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
];

export const institutionalReportTypes = [
  {
    id: 'ia-application-form',
    title: 'Institutional Accreditation Application Form',
    titleAr: 'نموذج التقدم للاعتماد المؤسسي',
    descEn: 'Institutional application package for accreditation submission',
    desc: 'نموذج وبيانات التقدم للاعتماد المؤسسي',
    icon: 'ti-file-description',
    iconClass: 'ic-primary',
    highlight: 'hl-primary',
    badge: { label: 'Pending', cls: 'b-primary' },
    defaultStatus: 's-pending',
    defaultStatusLabel: 'Pending Submit',
    category: 'main',
  },
  {
    id: 'ia-review-visit-documents',
    title: 'Required Documents for Review Visit',
    titleAr: 'الوثائق المطلوبة لزيارة المراجعة',
    descEn: 'Documents required before and during the institutional review visit',
    desc: 'الوثائق المطلوبة قبل وأثناء زيارة المراجعة',
    icon: 'ti-folders',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'ia-recommendations-response',
    title: 'Response to Accreditation Recommendations and Information Errors',
    titleAr: 'استجابة المؤسسات نحو توصيات الاعتماد والأخطاء المعلوماتية',
    descEn: 'Institutional response to recommendations and information corrections',
    desc: 'استجابة المؤسسة لتوصيات الاعتماد وتصحيح الأخطاء المعلوماتية',
    icon: 'ti-message-report',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'ia-standards',
    title: 'Accreditation Standards for Higher Education Institutions',
    titleAr: 'معايير الاعتماد لمؤسسات التعليم العالي',
    descEn: 'Institutional accreditation standards and compliance evidence',
    desc: 'معايير الاعتماد المؤسسي وشواهد الاستيفاء',
    icon: 'ti-certificate',
    iconClass: 'ic-amber',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'main',
  },
  {
    id: 'ia-kpis',
    title: 'Key Performance Indicators for Higher Education Institutions',
    titleAr: 'مؤشرات الأداء الرئيسية لمؤسسات التعليم العالي',
    descEn: 'Institutional KPIs, trends, measures, and evidence',
    desc: 'مؤشرات الأداء المؤسسية والقياسات والاتجاهات والشواهد',
    icon: 'ti-target',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-inprogress',
    defaultStatusLabel: 'In Progress',
    category: 'main',
  },
  {
    id: 'ia-improvement-plan',
    title: 'Improvement Plan for Accreditation Recommendations',
    titleAr: 'خطة التحسين لتوصيات الاعتماد',
    descEn: 'Improvement plan responding to accreditation recommendations',
    desc: 'خطة التحسين المرتبطة بتوصيات الاعتماد',
    icon: 'ti-progress-check',
    iconClass: 'ic-green',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'ia-eligibility-report',
    title: 'Institutional Accreditation Eligibility Fulfillment Report',
    titleAr: 'تقرير استيفاء شروط الاعتماد المؤسسي',
    descEn: 'Report on fulfilling institutional accreditation eligibility requirements',
    desc: 'تقرير استيفاء شروط ومتطلبات الاعتماد المؤسسي',
    icon: 'ti-clipboard-check',
    iconClass: 'ic-primary',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'ia-basic-data-followup',
    title: 'Basic Data and Performance Indicators Form - Follow-up',
    titleAr: 'نموذج البيانات الأساسية ومؤشرات الأداء للمؤسسات المعتمدة - المتابعة',
    descEn: 'Basic data and performance indicator follow-up form',
    desc: 'نموذج المتابعة للبيانات الأساسية ومؤشرات الأداء',
    icon: 'ti-list-details',
    iconClass: 'ic-purple',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'ia-self-study',
    title: 'Institutional Self-Study Report',
    titleAr: 'تقرير الدراسة الذاتية للمؤسسة',
    descEn: 'Institutional self-study report against accreditation standards',
    desc: 'تقرير الدراسة الذاتية للمؤسسة مقابل معايير الاعتماد',
    icon: 'ti-microscope',
    iconClass: 'ic-amber',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'ia-periodic-followup',
    title: 'Periodic Follow-up Report for Accredited Institutions',
    titleAr: 'تقرير المتابعة الدورية للمؤسسات المعتمدة',
    descEn: 'Periodic follow-up report for accredited institutions',
    desc: 'تقرير المتابعة الدورية للمؤسسات المعتمدة',
    icon: 'ti-calendar-stats',
    iconClass: 'ic-teal',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
  {
    id: 'ia-substantial-changes',
    title: 'Substantial Changes Report for Accredited Institutions',
    titleAr: 'تقرير التغيرات الجوهرية للمؤسسات المعتمدة',
    descEn: 'Report substantial institutional changes after accreditation',
    desc: 'تقرير التغيرات الجوهرية للمؤسسات المعتمدة',
    icon: 'ti-arrows-exchange',
    iconClass: 'ic-coral',
    highlight: '',
    badge: null,
    defaultStatus: 's-not-started',
    defaultStatusLabel: 'Not Started',
    category: 'additional',
  },
];

export const historyItems = [
  { year: '2024/2025', date: 'Submitted 14 Jan 2025', status: 's-pending', statusLabel: 'Pending Submit', action: 'view' },
  { year: '2023/2024', date: 'Approved 8 Feb 2024',   status: 's-done',    statusLabel: 'Approved',       action: 'view' },
  { year: '2022/2023', date: 'Archived',               status: 's-archived',statusLabel: 'Archived',       action: 'view' },
];
